version: "3.8"
services:
  chrony:
    image: chrony/chrony:latest
    container_name: toc_timesync
    network_mode: host
    cap_add:
      - SYS_TIME
    volumes:
      - ./chrony/chrony.conf:/etc/chrony/chrony.conf:ro

  sdr:
    build: ./sdr-pipeline
    container_name: toc_sdr
    network_mode: host
    privileged: true                # needed to access USB
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - PULSE_SERVER=unix:/tmp/pulse/native
    volumes:
      - /tmp/pulse:/tmp/pulse
    command: >
      sh -c "rtl_fm -f 7.078000M -M usb -s 12k -g 25 \
        | sox -t wav -r 12k -e signed -b 16 -c 1 - -t pulse js8loop"

  js8call:
    build: ./js8call
    container_name: toc_js8
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/tmp/pulse/native
    devices:
      - /tmp/pulse:/tmp/pulse
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - js8-log:/home/js8/.js8call
    depends_on:
      - sdr

volumes:
  js8-log:
